/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : EventId,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'date' : Time,
  'description' : string,
  'location' : [] | [string],
}
export type EventId = bigint;
export interface Note {
  'id' : NoteId,
  'title' : string,
  'created' : Time,
  'content' : string,
  'lastModified' : [] | [Time],
  'isPrivate' : boolean,
}
export type NoteId = bigint;
export interface Settings { 'darkMode' : boolean }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / EVENTS
   */
  'createEvent' : ActorMethod<
    [string, string, Time, bigint, bigint, [] | [string]],
    Event
  >,
  /**
   * / NOTES
   */
  'createNote' : ActorMethod<[string, string, boolean], NoteId>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'editNote' : ActorMethod<[NoteId, string, string], Note>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  /**
   * / TYPES
   */
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[EventId], Event>,
  'getEventsForDay' : ActorMethod<[Time], Array<Event>>,
  'getNote' : ActorMethod<[NoteId], Note>,
  /**
   * / SETTINGS
   */
  'getUserSettings' : ActorMethod<[], Settings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveUserSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];