/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EventId = IDL.Nat;
export const Event = IDL.Record({
  'id' : EventId,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const NoteId = IDL.Nat;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'created' : Time,
  'content' : IDL.Text,
  'lastModified' : IDL.Opt(Time),
  'isPrivate' : IDL.Bool,
});
export const Settings = IDL.Record({ 'darkMode' : IDL.Bool });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [Event],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NoteId], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'editNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [Note], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([EventId], [Event], ['query']),
  'getEventsForDay' : IDL.Func([Time], [IDL.Vec(Event)], ['query']),
  'getNote' : IDL.Func([NoteId], [Note], ['query']),
  'getUserSettings' : IDL.Func([], [Settings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveUserSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EventId = IDL.Nat;
  const Event = IDL.Record({
    'id' : EventId,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const NoteId = IDL.Nat;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'created' : Time,
    'content' : IDL.Text,
    'lastModified' : IDL.Opt(Time),
    'isPrivate' : IDL.Bool,
  });
  const Settings = IDL.Record({ 'darkMode' : IDL.Bool });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [Event],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NoteId], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'editNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [Note], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([EventId], [Event], ['query']),
    'getEventsForDay' : IDL.Func([Time], [IDL.Vec(Event)], ['query']),
    'getNote' : IDL.Func([NoteId], [Note], ['query']),
    'getUserSettings' : IDL.Func([], [Settings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveUserSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };